export enum UI_ICON {
  MENU = `menu`,
  PRODUCT = `box`,
  CATEGORY = `package`,
  PROMOTION = `shopping-bag`,
  SHOP = `shopping-cart`,
  PAYMENT = `dollar-sign`,
  DELIVERY = `truck`,
  USER = `user`,
  LOG_OUT = `log-out`,
  ARROW_LEFT = `arrow-left`,
  ARROW_RIGHT = `arrow-right`,
  SEARCH = `search`,
  CLOSE = `x-circle`,
  DELETE = `trash-2`,
}